project: 'mongoid-manual'
master_doc: 'mongoid'
logo: ".static/logo.png"
paths:
  static: ['source/.static']
theme:
  name: 'meta-driver'
  project: 'docs-mongoid'
  google_analytics: 'UA-7301842-8'
  book_path_base: 'mongoid'
  repo: 'docs-mongoid'
  jira: 'DOCS'
  sitename: 'Mongoid'
  nav_excluded:
     - /mongoid-tutorials
sidebars:
  '**':
    - 'pagenav.html'
...